[project]
name = "study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "catboost>=1.2.10",
    "ipykernel>=7.3.0",
    "lightgbm>=4.7.0",
    "matplotlib>=3.5.0,<=3.10.0",
    "numpy>=1.24.0,<2.2.0",
    "optuna>=4.9.0",
    "pandas>=2.2.0,<3.0.0",
    "ruff>=0.16.1",
    "scikit-learn>=1.5.0",
    "setuptools>=70.0.0,<71.0.0",
    "shap>=0.51.0",
    "tensorflow>=2.21.0",
    "torch>=2.12.1",
    "xgboost>=3.2.0",
    "ydata-profiling>=4.18.4",
]

[tool.ruff]
line-length = 100
extend-include = ["*.ipynb"]

[tool.ruff.lint]
extend-select = ["I", "F"]

[tool.ruff.lint.per-file-ignores]
"*.ipynb" = [
    "E402",  # Разрешаем импорты в середине ноутбука
    "F401",  # ИГНОРИРОВАТЬ неиспользуемые импорты (не подсвечивать и не удалять)
]
