[project]
name = "study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
# 1. Ограничиваем сверху, чтобы uv не искал зависимости для Python 3.14+
requires-python = ">=3.11, <3.13"
dependencies = [
    "catboost>=1.2.10",
    "ipykernel>=7.3.0",
    "lightgbm>=4.7.0",
    "optuna>=4.9.0",
    "pandas>=2.2.0,<3.0.0",
    "ruff>=0.16.1",
    "scikit-learn>=1.5.0",
    "setuptools>=70.0.0,<71.0.0",
    "shap>=0.51.0",
    "tensorflow>=2.21.0",
    "torch>=2.12.1",
    "xgboost>=3.2.0",
    "ydata-profiling>=4.12.0", # Расширили совместимость вниз
    "imageio>=2.37.4",
    "matplotlib>=3.8.0,<3.10", # 2. Понизили до диапазона, который просит ydata-profiling
    "numpy>=1.26.0,<3.0.0",    # 3. Расширили диапазон для стабильности ML-пакетов
    "pillow>=10.0.0",
    "psutil>=5.9.0",
    "scipy>=1.11.0",
]
